---
- name: Manage the schedulled job
  hosts: student1-win1
  gather_facts: false
  tasks:
    - name: Enable the schedullar job
      win_shell: Enable-ScheduledTask -TaskName {{ taskname }} -TaskPath {{ taskpath }}
      when: "{{ input }}" == "Enable"
    - name: Disable the schedullar job
      win_shell: Disable-ScheduledTask -TaskName {{ taskname }} -TaskPath {{ taskpath }}
      when: {{ input }} == "Disable"      
