---
- name: Capture Job Report
  hosts: student1-win1
  tasks:
    - name: Capture all the tasks details
      win_shell: Get-ScheduledTask
      register: jobs
    - name: Display Job Details
      ansible.builtin.debug:
        var: jobs
        verbosity: 2
